name: CI
on:
  push:
    branches: master
  pull_request:

jobs:
  tests:
    runs-on: macos-latest

    steps:
      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - name: Cache Homebrew Bundler RubyGems
        id: cache
        uses: actions/cache@v1
        with:
          path: ${{ steps.set-up-homebrew.outputs.gems-path }}
          key: ${{ runner.os }}-rubygems-${{ steps.set-up-homebrew.outputs.gems-hash }}
          restore-keys: ${{ runner.os }}-rubygems-

      - name: Install Homebrew Bundler RubyGems
        if: steps.cache.outputs.cache-hit != 'true'
        run: brew install-bundler-gems

      - env:
          HOMEBREW_ADOBE_AE_MOTION: ${{ secrets.HOMEBREW_ADOBE_AE_MOTION }}
          HOMEBREW_ADOBE_AE_PRESET_CONIGS_MIXTAPE: ${{ secrets.HOMEBREW_ADOBE_AE_PRESET_CONIGS_MIXTAPE }}
          HOMEBREW_ADOBE_COOLORS: ${{ secrets.HOMEBREW_ADOBE_COOLORS }}
          HOMEBREW_ADOBE_FONTSELF: ${{ secrets.HOMEBREW_ADOBE_FONTSELF }}
          HOMEBREW_ADOBE_OVERLORD: ${{ secrets.HOMEBREW_ADOBE_OVERLORD }}
          HOMEBREW_ADOBE_RUBBERHOSE: ${{ secrets.HOMEBREW_ADOBE_RUBBERHOSE }}
          HOMEBREW_ADOBE_SHIFT_IN_TIME: ${{ secrets.HOMEBREW_ADOBE_SHIFT_IN_TIME }}

        run: .github/hooks/pre-commit

      - name: Upload bottles as artifact
        if: always() && github.event_name == 'pull_request'
        uses: actions/upload-artifact@main
        with:
          name: bottles
          path: '*.bottle.*'
